name: project_color_palette
description: "This package is a tool for collaboration between designers and Flutter developers. csv to color_palette"
version: 1.0.0
homepage: "https://github.com/aqoong/aqoong-project_color_palette"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  build: ^2.4.1
  glob: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  source_gen_test: ^1.0.6
  build_runner: ^2.4.9

license: MIT